### ISSUE TITLE
Guide orientation is swapped

### ISSUE THREAD

**Issue by bzx** [petehouston/sketch-guides#1]
"Horizontal guide" command adds a vertical guide, and vice versa "vertical guide" command adds a horizontal guide.

Sketch 3.1.1

**Comment by petehouston** [comment]
No, actually it's kind of differrent from Photoshop. In Sketch, when you hover the horizontal ruler, and click on any value range, it will create a vertical guide line, and that is the horizontal guide.

**Comment by bzx** [comment]
I understand the difference between adding guides between PS and Sketch (and how this translates to writing the plugin for Sketch), but when choosing the option of your plugin from the dropdown I would like it to be logical, so when I choose "Add Horizontal" I want to get a horizontal guide, and I am getting vertical one (and vice versa). This doesn't make sense to me.

**Comment by bzx** [comment]
Hi, did you understand my explanation?
